image: python:3.5

build:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - flake8 .
  - python manage.py collectstatic --noinput
  - python manage.py test

  when: on_success
  only:
    - develop


production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby ruby-dev rubygems-integration
  - gem install dpl
  - dpl --provider=heroku --app=wall --api-key=$HEROKU_API_KEY
  only:
  - develop